
#include "../../../src/common_headers.h"

#include "../../../src/branch.h"
#include "../../../src/building.h"
#include "../../../src/documentation.h"
#include "../../../src/evaluation.h"
#include "../../../src/feedback.h"
#include "../../../src/filesystem.h"
#include "../../../src/handle.h"
#include "../../../src/if_block.h"
#include "../../../src/importing.h"
#include "../../../src/importing_macros.h"
#include "../../../src/introspection.h"
#include "../../../src/kernel.h"
#include "../../../src/list.h"
#include "../../../src/metaprogramming.h"
#include "../../../src/names.h"
#include "../../../src/source_repro.h"
#include "../../../src/static_checking.h"
#include "../../../src/string_type.h"
#include "../../../src/stateful_code.h"
#include "../../../src/switch_block.h"
#include "../../../src/tagged_value.h"
#include "../../../src/term.h"
#include "../../../src/token.h"
#include "../../../src/type.h"
#include "../../../src/type_inference.h"
#include "../../../src/update_cascades.h"

#include "../../../src/types/point.h"
#include "../../../src/types/ref.h"


