# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := library command_line

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

library: 
	@echo "==== Building library ($(config)) ===="
	@${MAKE} --no-print-directory -C src -f library.make

command_line: library
	@echo "==== Building command_line ($(config)) ===="
	@${MAKE} --no-print-directory -C src -f command_line.make

clean:
	@${MAKE} --no-print-directory -C src -f library.make clean
	@${MAKE} --no-print-directory -C src -f command_line.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   library"
	@echo "   command_line"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
