# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := static_lib command_line unit_tests

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

static_lib: 
	@echo "==== Building static_lib ($(config)) ===="
	@${MAKE} --no-print-directory -C src -f static_lib.make

command_line: static_lib
	@echo "==== Building command_line ($(config)) ===="
	@${MAKE} --no-print-directory -C src -f command_line.make

unit_tests: static_lib
	@echo "==== Building unit_tests ($(config)) ===="
	@${MAKE} --no-print-directory -C src -f unit_tests.make

clean:
	@${MAKE} --no-print-directory -C src -f static_lib.make clean
	@${MAKE} --no-print-directory -C src -f command_line.make clean
	@${MAKE} --no-print-directory -C src -f unit_tests.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   static_lib"
	@echo "   command_line"
	@echo "   unit_tests"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
