


from glob import glob

# Get source files


source_files = list(glob("src/*.cpp"))

circa_lib = StaticLibrary('circa', source_files, CPPFLAGS=['-ggdb'], 
    CPPDEFINES=['DEBUG'])


Program('test1', ['test1.cpp'], LIBS = [circa_lib])
