
import os,sys, glob

env = Environment()

DEBUG_BUILD = True
SOURCE_DIRECTORY = "src"

env.Append(CPPDEFINES = ["_DEBUG"])
env.Append(CPPDEFINES = ["DEBUG"])

def setup_windows_env():
    env.Append(CPPFLAGS=['/EHsc'])

    if DEBUG_BUILD:
        env.Append(LINKFLAGS = ['/DEBUG'])  # enable debugging information
        env.Append(LINKFLAGS = ['/NODEFAULTLIB:"LIBCMT.LIB"'])
        env.Append(LINKFLAGS = ['/NODEFAULTLIB:"LIBCPMT.LIB"'])
        env.Append(LINKFLAGS = ['/MACHINE:X86'])
        env.Append(CCFLAGS = ['/MD'])        # MSVCRT.LIB & MSVCPRT.LIB
        env.Append(CCFLAGS = ['/Od'])        # Disable optimizations
        env.Append(CCFLAGS = ['/Z7'])
        
def setup_mac_env():
    # Python support
    #env.Append(CPPPATH = ["/System/Library/Frameworks/Python.framework/Versions/2.5/Headers"])

    if DEBUG_BUILD:
        env.Append(CPPFLAGS=['-ggdb'])

setup_mac_env()

# Build everything in source directory
source_files = glob.glob(SOURCE_DIRECTORY + '/*.cpp')

env.SharedLibrary('circa', source_files)

