
import os



env = Environment()

env.ParseConfig('sdl-config --cflags')
env.ParseConfig('sdl-config --libs')

env.Append(LIBS = ['SDL_mixer', 'SDL_image'])


env.Append(CPPPATH = "../src")
env.Append(LIBPATH = "../lib")
env.Append(LIBS = ['circa'])

env.Program('main', ['main.cpp'], ['circa'])
