#!/bin/bash

cd $CIRCA_HOME
pl-r -gd docs.temp.json

python docs/nanodoc/nanohtml.py --doc docs.temp.json --output docs.temp.html

cp docs/nanodoc/nanodoc.css gh-pages/docs
cp docs/nanodoc/nanodoc.js gh-pages/docs
cp docs.temp.html gh-pages/docs/index.html

#rm docs.json.temp
