#!/bin/bash

cd $CIRCA_HOME
scons plastic

version_name=plastic_osx_cl_alpha1

target=build/deploy/$version_name

mkdir -p $target
rm -rf $target/*

cp build/bin/plas $target/plastic

cp -r plastic/assets $target
cp plastic/runtime.ca $target

cp -r plastic/demos $target
rm $target/demos/meshtest.ca
rm $target/demos/ramps.ca
rm $target/demos/tree.ca

cd $target
mkdir bin
mac_deploy_dylibs.py

zip_file=$CIRCA_HOME/build/$version_name.zip
rm $zip_file
cd $CIRCA_HOME/build/deploy
zip -r $zip_file $version_name
