#!/bin/bash

cd $CIRCA_HOME
pl-build && plas -gd docs.json.temp

python docs/nanodoc/nanohtml.py --doc docs.json.temp --output docs/nanodoc/index.html
#rm docs.json.temp

cp docs/nanodoc/nanodoc.css circa-web/_web/docs
cp docs/nanodoc/nanodoc.js circa-web/_web/docs
cp docs/nanodoc/index.html circa-web/_web/docs
