#!/usr/bin/env python

def generate(sourceFile, variableName):
    source = open(sourceFile)
    out = []

    out.append("// This file was autogenerated from "+sourceFile)
    out.append("")
    out.append("namespace circa {")
    out.append("")
    out.append("extern const char* "+variableName+" = ")

    while source:
        line = source.readline()
        if line == "": break
        line = line[:-1]
        out.append('    "' + line + '\\n"')

    out[-1] += ";"
    out.append("")
    out.append("} // namespace circa")
    out.append("")

    return "\n".join(out)

if __name__ == '__main__':
    import sys
    print generate(sys.argv[1], sys.argv[2])
