// Copyright (c) Andrew Fischer. See LICENSE file for license terms.

// This file was generated using name_tool.py

#pragma once

namespace circa {

const int name_None = 0;
const int name_File = 1;
const int name_Newline = 2;
const int name_Out = 3;
const int name_Unknown = 4;
const int name_Repeat = 5;
const int name_Success = 6;
const int name_Failure = 7;
const int name_FileNotFound = 8;
const int name_NotEnoughInputs = 9;
const int name_TooManyInputs = 10;
const int name_ExtraOutputNotFound = 11;
const int name_Default = 12;
const int name_ByDemand = 13;
const int name_Unevaluated = 14;
const int name_InProgress = 15;
const int name_Lazy = 16;
const int name_Consumed = 17;
const int name_Return = 18;
const int name_Continue = 19;
const int name_Break = 20;
const int name_Discard = 21;
const int name_InfixOperator = 22;
const int name_FunctionName = 23;
const int name_TypeName = 24;
const int name_TermName = 25;
const int name_Keyword = 26;
const int name_Whitespace = 27;
const int name_UnknownIdentifier = 28;
const int tok_Identifier = 29;
const int tok_Name = 30;
const int tok_Integer = 31;
const int tok_HexInteger = 32;
const int tok_Float = 33;
const int tok_String = 34;
const int tok_Color = 35;
const int tok_Bool = 36;
const int tok_LParen = 37;
const int tok_RParen = 38;
const int tok_LBrace = 39;
const int tok_RBrace = 40;
const int tok_LBracket = 41;
const int tok_RBracket = 42;
const int tok_Comma = 43;
const int tok_At = 44;
const int tok_AtDot = 45;
const int tok_Dot = 46;
const int tok_Star = 47;
const int tok_Question = 48;
const int tok_Slash = 49;
const int tok_DoubleSlash = 50;
const int tok_Plus = 51;
const int tok_Minus = 52;
const int tok_LThan = 53;
const int tok_LThanEq = 54;
const int tok_GThan = 55;
const int tok_GThanEq = 56;
const int tok_Percent = 57;
const int tok_Colon = 58;
const int tok_DoubleColon = 59;
const int tok_DoubleEquals = 60;
const int tok_NotEquals = 61;
const int tok_Equals = 62;
const int tok_PlusEquals = 63;
const int tok_MinusEquals = 64;
const int tok_StarEquals = 65;
const int tok_SlashEquals = 66;
const int tok_ColonEquals = 67;
const int tok_RightArrow = 68;
const int tok_LeftArrow = 69;
const int tok_Ampersand = 70;
const int tok_DoubleAmpersand = 71;
const int tok_DoubleVerticalBar = 72;
const int tok_Semicolon = 73;
const int tok_TwoDots = 74;
const int tok_Ellipsis = 75;
const int tok_TripleLThan = 76;
const int tok_TripleGThan = 77;
const int tok_Pound = 78;
const int tok_Def = 79;
const int tok_Type = 80;
const int tok_Begin = 81;
const int tok_Do = 82;
const int tok_End = 83;
const int tok_If = 84;
const int tok_Else = 85;
const int tok_Elif = 86;
const int tok_For = 87;
const int tok_State = 88;
const int tok_Return = 89;
const int tok_In = 90;
const int tok_True = 91;
const int tok_False = 92;
const int tok_DoOnce = 93;
const int tok_Namespace = 94;
const int tok_Include = 95;
const int tok_Import = 96;
const int tok_And = 97;
const int tok_OR = 98;
const int tok_Not = 99;
const int tok_Discard = 100;
const int tok_Null = 101;
const int tok_Break = 102;
const int tok_Continue = 103;
const int tok_Switch = 104;
const int tok_Case = 105;
const int tok_While = 106;
const int tok_Whitespace = 107;
const int tok_Newline = 108;
const int tok_Comment = 109;
const int tok_Eof = 110;
const int tok_Unrecognized = 111;
const int name_LastBuiltinName = 112;

const char* builtin_name_to_string(int name);

} // namespace circa
